import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, Camera, CheckCircle2, Loader2, MapPin, Send, X } from 'lucide-react';
import { MapContainer, Marker, TileLayer } from 'react-leaflet';
import { useTranslation } from 'react-i18next';
import api from '../services/axiosInstance';

export default function ReportIssuePage() {
  const { t } = useTranslation(); const n = useNavigate(); const [q] = useSearchParams();
  const [d, setD] = useState(''); const [p, setP] = useState(null); const [u, setU] = useState('');
  const [pos, setPos] = useState([20.5937, 78.9629]); const [gps, setGps] = useState(true); const [sub, setSub] = useState(false); const [ok, setOk] = useState(false);
  useEffect(() => { if (q.get('location')) setU(q.get('location')); }, [q]);
  const rev = async (lat, lng) => { const r = await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json`); const j = await r.json(); setU(j.display_name || ''); };
  useEffect(() => { navigator.geolocation?.getCurrentPosition(async (g) => { const p2 = [g.coords.latitude, g.coords.longitude]; setPos(p2); setGps(false); await rev(p2[0], p2[1]); }, () => setGps(false)); }, []);
  const send = async () => { if (!d.trim()) return; setSub(true); try { const f = new FormData(); f.append('description', d); f.append('location_lat', String(pos[0])); f.append('location_lng', String(pos[1])); f.append('location_address', u); if (p?.file) f.append('photo', p.file); if (q.get('bin_id')) f.append('bin_id', q.get('bin_id')); await api.post('/issues', f, { headers: { 'Content-Type': 'multipart/form-data' } }); setOk(true); } finally { setSub(false); } };
  if (ok) return <div className="min-h-screen text-black" style={{ backgroundColor:'var(--clay-bg)' }}><div className="relative min-h-screen w-full grid place-items-center px-4" style={{ backgroundColor:'var(--clay-bg)' }}><div className="text-center"><div className="mx-auto clay-icon mb-3 flex h-16 w-16 items-center justify-center" style={{ backgroundColor:'var(--clay-card)', color:'var(--clay-primary)' }}><CheckCircle2 className="h-9 w-9" /></div><h2 className="text-xl font-bold text-black">{t('reportIssue.successTitle',{defaultValue:'Report Submitted!'})}</h2><p className="mt-1 text-sm" style={{ color:'var(--clay-muted)' }}>{t('reportIssue.successMessage',{defaultValue:'A Safai Mitra will be assigned to your area soon.'})}</p><button onClick={()=>n('/dashboard')} className="mt-4 rounded-2xl px-5 py-3 text-sm font-semibold text-white" style={{ background:'linear-gradient(135deg,var(--clay-primary),var(--clay-secondary))' }}>{t('reportIssue.backToDashboard',{defaultValue:'Back to Dashboard'})}</button></div></div></div>;
  return <div className="min-h-screen text-black" style={{ backgroundColor:'var(--clay-bg)' }}><div className="relative min-h-screen w-full" style={{ backgroundColor:'var(--clay-bg)' }}>
    <header className="clay-header sticky top-0 z-20 flex items-center gap-3 px-4 py-3 sm:px-5 sm:py-4"><button type="button" onClick={()=>n(-1)} className="clay-btn-round inline-flex h-10 w-10 items-center justify-center text-black" aria-label="Go back"><ArrowLeft className="h-5 w-5" /></button><div className="flex items-center gap-2"><div className="clay-icon flex h-11 w-11 items-center justify-center overflow-hidden" style={{ backgroundColor:'#fff' }}><img src="/Logo.png" alt="GramWaste Connect" className="h-9 w-9 object-contain" /></div><div><p className="text-sm font-bold text-black sm:text-base">{t('reportIssue.title',{defaultValue:'Report a Problem'})}</p><p className="text-xs sm:text-sm" style={{ color:'var(--clay-muted)' }}>{t('reportIssue.subtitle',{defaultValue:'Help us keep your village clean'})}</p></div></div></header>
    <main className="mx-auto max-w-md space-y-3 px-4 py-4 pb-24">
      <section className="clay-card p-3"><div className="mb-2 flex items-center gap-2"><div className="clay-icon flex h-8 w-8 items-center justify-center" style={{ backgroundColor:'var(--clay-bg)', color:'var(--clay-primary)' }}><AlertTriangle className="h-4 w-4" /></div><p className="text-sm font-medium text-black">{t('reportIssue.descLabel',{defaultValue:'Describe the problem'})}</p></div><textarea rows={3} maxLength={500} value={d} onChange={(e)=>setD(e.target.value)} placeholder={t('reportIssue.descPlaceholder',{defaultValue:'E.g. Garbage overflowing near the school gate...'})} className="clay-lang-box w-full resize-none px-3 py-2 text-sm text-black outline-none" /><p className="mt-1 text-right text-xs" style={{ color:'var(--clay-muted)' }}>{d.length} / 500</p></section>
      <section className="clay-card p-3"><div className="mb-2 flex items-center gap-2"><Camera className="h-4 w-4" style={{ color:'var(--clay-primary)' }} /><p className="text-sm font-medium text-black">{t('reportIssue.photoLabel',{defaultValue:'Add a Photo'})}</p></div>{!p ? <label className="block cursor-pointer rounded-2xl border-2 border-dashed p-6 text-center" style={{ borderColor:'var(--clay-card-alt)' }}><Camera className="mx-auto h-6 w-6" style={{ color:'var(--clay-muted)' }} /><p className="mt-1 text-xs" style={{ color:'var(--clay-muted)' }}>{t('reportIssue.tapToAddPhoto',{defaultValue:'Tap to add photo'})}</p><input type="file" accept="image/*" capture="environment" className="hidden" onChange={(e)=>{const f=e.target.files?.[0]; if(f) setP({file:f,url:URL.createObjectURL(f)});}} /></label> : <div className="relative"><img src={p.url} alt="report" className="aspect-video w-full rounded-xl object-cover" /><button type="button" onClick={()=>setP(null)} className="absolute right-2 top-2 clay-btn-round inline-flex h-7 w-7 items-center justify-center"><X className="h-3 w-3" /></button></div>}</section>
      <section className="clay-card p-3"><div className="mb-2 flex items-center gap-2"><MapPin className="h-4 w-4" style={{ color:'var(--clay-primary)' }} /><p className="text-sm font-medium text-black">{t('reportIssue.locationLabel',{defaultValue:'Your Location'})}</p></div>{gps?<p className="inline-flex items-center gap-1 text-xs" style={{ color:'var(--clay-muted)' }}><Loader2 className="h-3 w-3 animate-spin" />{t('reportIssue.detectingLocation',{defaultValue:'Detecting location...'})}</p>:<><p className="mb-2 text-xs" style={{ color:'var(--clay-muted)' }}>{u || '-'}</p><div className="h-[180px] overflow-hidden rounded-xl"><MapContainer center={pos} zoom={15} style={{height:'100%',width:'100%'}}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Marker position={pos} draggable eventHandlers={{ dragend: async (e)=>{const ll=e.target.getLatLng(); const p2=[ll.lat,ll.lng]; setPos(p2); await rev(p2[0],p2[1]);} }} /></MapContainer></div></>}</section>
      <button type="button" onClick={send} disabled={sub || !d.trim()} className="flex h-[52px] w-full items-center justify-center gap-2 rounded-2xl text-sm font-semibold text-white disabled:opacity-70" style={{ background:'linear-gradient(135deg,var(--clay-primary),var(--clay-secondary))' }}>{sub?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}{t('reportIssue.submitBtn',{defaultValue:'Submit Report'})}</button>
    </main></div></div>;
}
